#!/usr/bin/env python3
"""
Applies hand-crafted meaningful sentences for the 295 flagged words
that the Free Dictionary API could not find examples for.

Usage:
    python3 apply_flagged_sentences.py
"""

import json
from pathlib import Path

VOCAB_JSON_PATH = Path(__file__).parent.parent / "composeApp/src/commonMain/composeResources/files/vocabulary.json"

SENTENCES = {
    # ── A1 ────────────────────────────────────────────────────────────────────
    "afternoon":   ["Let's meet at the park this afternoon.", "She takes a short nap every afternoon.", "The afternoon sun was warm and bright."],
    "airport":     ["We arrived at the airport two hours early.", "The airport was crowded with holiday travelers.", "He waved goodbye at the airport entrance."],
    "apple":       ["She packed an apple in her lunch bag.", "An apple a day keeps the doctor away.", "He picked a red apple from the tree."],
    "baseball":    ["They played baseball in the park after school.", "He hit the baseball over the fence.", "Baseball is one of the most popular sports in America."],
    "beach":       ["We spent the whole day relaxing at the beach.", "The children built sandcastles on the beach.", "Let's watch the sunset from the beach tonight."],
    "begin":       ["Class will begin at nine o'clock sharp.", "She took a deep breath and began to speak.", "Let's begin with the easiest questions first."],
    "bicycle":     ["He rides his bicycle to school every day.", "She got a new bicycle for her birthday.", "Always wear a helmet when riding a bicycle."],
    "birthday":    ["Happy birthday! I hope you have a wonderful day.", "We threw a surprise birthday party for her.", "What would you like for your birthday this year?"],
    "bread":       ["She baked fresh bread for the family.", "Can you buy a loaf of bread at the store?", "He spread butter on a thick slice of bread."],
    "camera":      ["She brought her camera to capture the memories.", "He forgot his camera at home and missed great shots.", "This camera takes very sharp and clear photos."],
    "candle":      ["She lit a candle to make the room feel cozy.", "The power went out so we used candles for light.", "He blew out the birthday candle and made a wish."],
    "classroom":   ["The classroom was quiet during the exam.", "She decorated the classroom with colorful posters.", "Every student in the classroom raised their hand."],
    "cookie":      ["She baked chocolate chip cookies for the kids.", "Can I have one more cookie, please?", "He ate a warm cookie straight from the oven."],
    "country":     ["She has traveled to more than twenty countries.", "Which country do you come from?", "This country is known for its beautiful mountains."],
    "daily":       ["Exercise should be part of your daily routine.", "She reads the news daily to stay informed.", "Drinking enough water is a daily necessity."],
    "desk":        ["He sat at his desk and opened his laptop.", "She keeps her desk clean and well-organized.", "There is a pile of papers on his desk."],
    "drawer":      ["She found the keys in the top drawer.", "He keeps his socks in the bottom drawer.", "The drawer was stuck and hard to open."],
    "eat":         ["We usually eat dinner together as a family.", "You should eat more vegetables every day.", "Did you eat breakfast before coming to school?"],
    "everybody":   ["Everybody clapped at the end of the show.", "Is everybody ready to start the game?", "Everybody makes mistakes from time to time."],
    "example":     ["Can you give me an example of what you mean?", "She set a good example for the younger students.", "For example, you can use this word in a sentence."],
    "golf":        ["He plays golf every weekend with his friends.", "Golf requires patience and good concentration.", "She took golf lessons to improve her swing."],
    "grandfather": ["My grandfather tells amazing stories from his youth.", "She visits her grandfather every Sunday afternoon.", "His grandfather taught him how to fish."],
    "grandmother": ["My grandmother makes the best apple pie.", "She calls her grandmother every evening.", "His grandmother gave him a warm hug at the door."],
    "grocery":     ["She made a grocery list before going to the store.", "He forgot to buy milk at the grocery store.", "They do their grocery shopping on Saturday mornings."],
    "guitar":      ["He plays the guitar in a local band.", "She practiced guitar for an hour every evening.", "Learning to play the guitar takes time and dedication."],
    "hospital":    ["She visited her friend in the hospital.", "He was taken to the hospital after the accident.", "The hospital has excellent doctors and nurses."],
    "kitchen":     ["The whole family gathered in the kitchen to cook.", "She cleaned the kitchen after dinner.", "The kitchen smelled wonderful from the baking bread."],
    "knife":       ["He used a sharp knife to slice the vegetables.", "Always be careful when handling a knife.", "She placed the knife and fork beside the plate."],
    "lake":        ["They went fishing at the lake early in the morning.", "The lake was calm and reflected the blue sky.", "She swam across the lake on a hot summer day."],
    "look":        ["Look both ways before crossing the street.", "She looked out the window and saw the snow falling.", "He gave her a surprised look when she entered."],
    "mall":        ["They spent the afternoon shopping at the mall.", "The mall was packed with people during the holidays.", "She met her friends at the food court in the mall."],
    "march":       ["The soldiers began to march in perfect formation.", "She marched confidently onto the stage.", "They marched through the streets to show their support."],
    "midnight":    ["The party lasted until midnight.", "At midnight, fireworks lit up the sky.", "She stayed up until midnight finishing her project."],
    "mom":         ["His mom always packs him a healthy lunch.", "She called her mom as soon as she arrived safely.", "My mom taught me to cook when I was young."],
    "nervous":     ["She felt nervous before her job interview.", "He was so nervous that his hands were shaking.", "It is normal to feel nervous before a big exam."],
    "orange":      ["She peeled an orange and shared it with her brother.", "He drank a glass of fresh orange juice.", "The sunset turned the sky a beautiful shade of orange."],
    "oven":        ["She preheated the oven before putting in the cake.", "The pizza needs to bake in the oven for twenty minutes.", "Be careful — the oven door is very hot."],
    "parent":      ["Every parent wants the best for their children.", "Her parents supported her decision to study abroad.", "A good parent listens as well as guides."],
    "phone":       ["She left her phone on the bus by accident.", "Can I borrow your phone to make a quick call?", "He checks his phone first thing every morning."],
    "photo":       ["She took a photo of the sunset to remember it.", "They printed a large photo for the living room wall.", "He scrolled through old photos and smiled."],
    "plane":       ["The plane landed safely despite the strong winds.", "She fell asleep on the plane and missed the meal.", "They watched the plane disappear into the clouds."],
    "popular":     ["This song is very popular among teenagers.", "She became popular in school because of her kindness.", "The new café is popular because of its great coffee."],
    "potato":      ["He peeled the potatoes for the soup.", "Mashed potato is one of her favorite comfort foods.", "She baked a potato and topped it with cheese."],
    "queen":       ["The queen greeted the crowd from the balcony.", "She was crowned queen at the age of twenty-five.", "The queen's speech was watched by millions of people."],
    "quite":       ["The exam was quite difficult for most students.", "She is quite talented at painting.", "It is quite cold outside today — bring a jacket."],
    "restaurant":  ["They went to a nice restaurant to celebrate.", "The restaurant was fully booked for the weekend.", "She recommended the pasta at that Italian restaurant."],
    "rice":        ["Rice is eaten with almost every meal in many countries.", "She cooked a big pot of rice for the family.", "He ordered fried rice with vegetables."],
    "salad":       ["She made a fresh salad with tomatoes and cucumbers.", "A green salad is a healthy start to any meal.", "He added lemon juice to the salad for extra flavor."],
    "sandwich":    ["She made a cheese and tomato sandwich for lunch.", "He grabbed a sandwich on the way to work.", "A club sandwich is his favorite thing to order."],
    "several":     ["She called him several times but got no answer.", "There are several ways to solve this problem.", "He visited the museum several times during his trip."],
    "shoulder":    ["She tapped him on the shoulder to get his attention.", "He carried the heavy bag on his shoulder.", "She rested her head on his shoulder during the film."],
    "silly":       ["Stop being silly and focus on your work.", "The children laughed at the silly joke.", "She made a silly face to cheer him up."],
    "simple":      ["The recipe is simple and takes only ten minutes.", "He explained the concept in simple, clear words.", "Sometimes the simplest solution is the best one."],
    "singer":      ["She is a talented singer with a powerful voice.", "The singer performed three songs at the concert.", "He dreamed of becoming a famous singer one day."],
    "sock":        ["He could only find one sock under the bed.", "She bought a pack of colorful socks.", "Always wear clean socks when you exercise."],
    "steak":       ["He ordered a medium-rare steak at the restaurant.", "She cooked the steak with garlic and butter.", "The steak was tender and full of flavor."],
    "teacher":     ["Her teacher praised her for working so hard.", "A great teacher can change a student's life.", "He thanked his teacher for the extra help."],
    "telephone":   ["She answered the telephone on the second ring.", "The telephone rang just as he was leaving.", "In the past, every home had a landline telephone."],
    "tennis":      ["She plays tennis every Saturday morning.", "They watched the tennis final together on TV.", "He bought a new tennis racket to practice with."],
    "tiny":        ["The tiny kitten fit in the palm of her hand.", "She lives in a tiny but cozy apartment.", "Even a tiny mistake can lead to big problems."],
    "touch":       ["Don't touch the paintings in the gallery.", "She touched the soft fabric and smiled.", "He was touched by her kind words."],
    "uncle":       ["My uncle always brings gifts when he visits.", "She spent the summer at her uncle's farm.", "His uncle taught him how to ride a bike."],
    "visit":       ["They plan to visit Paris next summer.", "She visited her grandmother every Sunday.", "He came to visit his old friends from university."],
    "woman":       ["A woman in a red coat waved from across the street.", "She is a strong and determined woman.", "The woman smiled warmly and offered to help."],

    # ── A2 ────────────────────────────────────────────────────────────────────
    "additional":   ["You may need additional time to finish the project.", "She requested additional information before deciding.", "The company hired additional staff for the busy season."],
    "apartment":    ["She rents a small apartment near the city center.", "They moved into a new apartment last month.", "The apartment has two bedrooms and a balcony."],
    "benefit":      ["Regular exercise has many benefits for your health.", "One benefit of working from home is saving travel time.", "She learned about the benefits of a healthy diet."],
    "boyfriend":    ["She introduced her boyfriend to her parents.", "Her boyfriend surprised her with flowers on her birthday.", "They have been boyfriend and girlfriend for two years."],
    "chemical":     ["The chemical reaction produced a bright blue color.", "Some cleaning products contain harmful chemicals.", "He studied chemical engineering at university."],
    "chemistry":    ["She got the highest mark in chemistry class.", "The chemistry between the two actors made the film great.", "Understanding chemistry helps us make sense of the world."],
    "competitive":  ["The job market is very competitive right now.", "He is a competitive player who always wants to win.", "She trained hard to stay competitive in her field."],
    "computer":     ["She uses her computer for work and studying.", "He bought a new computer because the old one was slow.", "Learning computer skills is important in today's world."],
    "currently":    ["She is currently studying for her final exams.", "The project is currently on hold due to budget issues.", "He currently works as a nurse at the local hospital."],
    "data":         ["The research team collected data from a thousand people.", "She analyzed the data carefully before writing her report.", "Your personal data should always be kept secure."],
    "despite":      ["Despite the rain, they went ahead with the picnic.", "She succeeded despite facing many challenges.", "He stayed calm despite the difficult situation."],
    "driver":       ["The bus driver greeted everyone with a smile.", "She is an excellent driver with a perfect safety record.", "The delivery driver knocked on the door twice."],
    "economy":      ["The country's economy has grown steadily this year.", "Rising prices are affecting the economy.", "A strong economy creates more jobs for people."],
    "electrical":   ["There was an electrical fault that caused a blackout.", "He called an electrician to fix the electrical problem.", "The electrical wiring in old buildings can be dangerous."],
    "electronic":   ["Electronic payments are faster and more convenient.", "She bought a new electronic keyboard for her music lessons.", "Electronic devices should be turned off during the flight."],
    "energy":       ["She had so much energy after a good night's sleep.", "Renewable energy sources like wind and solar are growing fast.", "He did not have enough energy to go to the gym after work."],
    "everyone":     ["Everyone clapped when she finished her speech.", "Not everyone agrees with the new policy.", "She made sure everyone had enough food at the party."],
    "exist":        ["Some people believe that ghosts do not exist.", "The problem has existed for many years without a solution.", "We must protect endangered species that still exist today."],
    "experienced":  ["We are looking for an experienced chef to join our team.", "She felt more confident after becoming experienced in her role.", "An experienced teacher knows how to handle difficult situations."],
    "extremely":    ["The weather was extremely cold last winter.", "She was extremely happy when she passed her driving test.", "The exam was extremely challenging for all the students."],
    "failure":      ["Failure is not the end — it is a chance to learn.", "The launch was considered a failure because of the technical issues.", "He refused to accept failure and tried again."],
    "function":     ["The main function of the heart is to pump blood.", "This button does not seem to function properly.", "Each part of the machine has its own specific function."],
    "growth":       ["The company showed impressive growth this year.", "Good nutrition is essential for a child's growth.", "She tracked her personal growth in a journal."],
    "helpful":      ["The staff were very helpful and friendly.", "He gave her some helpful advice about the interview.", "A helpful attitude makes a big difference at work."],
    "income":       ["She saves a portion of her income every month.", "His income increased after he got a promotion.", "They struggled to pay their bills on a low income."],
    "library":      ["She went to the library to study for her exams.", "He borrowed three books from the library last week.", "The library has a quiet section for reading and focus."],
    "location":     ["The restaurant is in a great location near the park.", "Please share your location so I can find you.", "They chose the location for the wedding carefully."],
    "magazine":     ["She reads a fashion magazine every month.", "He found an interesting article in a science magazine.", "The magazine published a story about sustainable living."],
    "maintain":     ["It is important to maintain a healthy lifestyle.", "He works hard to maintain his good grades.", "The team maintains the equipment to keep it working well."],
    "officer":      ["The police officer directed traffic at the busy junction.", "She was promoted to senior officer after five years.", "The officer asked to see his identification."],
    "payment":      ["She made the payment online using her credit card.", "The payment is due at the end of the month.", "He set up automatic payments so he never forgets."],
    "phase":        ["The project is now in its final phase.", "She went through a difficult phase after moving to a new city.", "The first phase of construction is almost complete."],
    "plastic":      ["Many shops no longer offer plastic bags.", "She replaced her plastic bottles with reusable ones.", "Plastic pollution is a serious environmental problem."],
    "primarily":    ["This service is designed primarily for young professionals.", "She is primarily responsible for managing the team.", "The film is primarily aimed at children under ten."],
    "probably":     ["It will probably rain this afternoon.", "She is probably the best student in the class.", "He is probably stuck in traffic — let's wait a few more minutes."],
    "professional": ["She handles all situations in a calm and professional way.", "He hired a professional photographer for the wedding.", "Always dress professionally for a job interview."],
    "proper":       ["Make sure to use proper grammar in your writing.", "You need proper training before using this equipment.", "She gave the wound proper care to prevent infection."],
    "radio":        ["She listens to the radio on her way to work.", "The news was announced on the radio early in the morning.", "He fixed the old radio and it worked perfectly again."],
    "refer":        ["Please refer to the instructions on page three.", "She referred to her notes during the presentation.", "You can refer to this guide whenever you need help."],
    "rely":         ["You can always rely on her to keep a promise.", "He relies on public transport to get to work.", "Don't rely too much on others — build your own skills."],
    "require":      ["This job requires at least three years of experience.", "The recipe requires fresh ingredients.", "Driving in this country requires an international license."],
    "risk":         ["There is always some risk involved in starting a business.", "She took a risk and it paid off in the end.", "He avoided unnecessary risks during the dangerous climb."],
    "section":      ["Please read the first section of the chapter tonight.", "The supermarket has a section dedicated to organic food.", "She works in the marketing section of the company."],
    "security":     ["The building has tight security with cameras everywhere.", "Online security is very important for protecting your data.", "He felt a strong sense of security in his new job."],
    "seem":         ["She seems tired today — maybe she didn't sleep well.", "It seems like it might snow later this evening.", "The task seemed difficult at first but got easier with practice."],
    "similar":      ["Their opinions on the topic are very similar.", "She found a similar dress at a much lower price.", "The two cities have a similar culture and history."],
    "skill":        ["Communication is one of the most valuable skills to have.", "She developed her writing skill by practicing every day.", "Learning a new skill takes time, effort, and patience."],
    "slowly":       ["She spoke slowly so everyone could understand her.", "The old car climbed the hill slowly.", "Progress was slow, but they moved forward steadily."],
    "software":     ["The software update fixed many bugs in the app.", "He works as a software developer at a tech company.", "Make sure your software is always up to date."],
    "solve":        ["She worked for hours trying to solve the math problem.", "We need to solve this issue before it gets worse.", "Talking openly is often the best way to solve a conflict."],
    "space":        ["She needs some space to think clearly.", "The apartment doesn't have much space for a large sofa.", "Astronauts train for years before traveling to space."],
    "specifically": ["He was hired specifically to manage social media.", "She asked him specifically not to mention the surprise party.", "This product is designed specifically for sensitive skin."],
    "statement":    ["The company released a statement about the incident.", "She made a bold statement with her choice of outfit.", "His bank statement showed all his recent transactions."],
    "style":        ["She has a unique sense of style that everyone admires.", "His writing style is clear and easy to follow.", "The café has a cozy and relaxed style."],
    "technology":   ["Technology has changed the way we communicate.", "She is excited about new technology in healthcare.", "Children today grow up surrounded by technology."],
    "throughout":   ["She stayed calm throughout the entire interview.", "It rained throughout the day without stopping.", "He worked hard throughout his career to reach the top."],
    "useful":       ["This dictionary app is very useful for language learners.", "She gave him some useful tips for the exam.", "A map is very useful when you are visiting a new city."],
    "user":         ["The app is designed to be easy for any user.", "Each user gets their own personal account.", "She read the user guide before setting up the device."],
    "video":        ["She recorded a short video of the sunset.", "He watched a tutorial video to learn how to cook.", "The video went viral and was shared millions of times."],
    "western":      ["She loves watching western movies set in the old American frontier.", "Western culture has had a big influence on fashion.", "He studied western philosophy at university."],
    "widely":       ["This method is widely used in medical research.", "She is widely regarded as one of the best in her field.", "The news spread widely within hours of being published."],

    # ── B1 ────────────────────────────────────────────────────────────────────
    "actor":        ["He is a talented actor who has won several awards.", "She studied acting for years before becoming a professional actor.", "The actor gave an emotional performance in the final scene."],
    "agent":        ["The real estate agent showed them three apartments.", "She hired a literary agent to help sell her book.", "The secret agent completed the mission without being seen."],
    "airline":      ["The airline announced a delay due to bad weather.", "She works for an international airline as a flight attendant.", "He booked his tickets directly through the airline's website."],
    "alcohol":      ["He decided to stop drinking alcohol for health reasons.", "Some medicines should not be taken with alcohol.", "The restaurant does not serve alcohol to anyone under eighteen."],
    "analyst":      ["The financial analyst predicted growth in the market.", "She works as a data analyst for a large tech firm.", "The analyst reviewed the figures before presenting his findings."],
    "announce":     ["The company announced a major new product launch.", "She announced her engagement to her family at dinner.", "The teacher announced that the exam would be postponed."],
    "assistance":   ["He offered his assistance to the elderly woman.", "Please call this number if you need any assistance.", "The charity provides financial assistance to families in need."],
    "assistant":    ["She works as a personal assistant to the director.", "The assistant brought in the documents for the meeting.", "He was hired as a teaching assistant at the university."],
    "automatically": ["The door opens automatically when you approach it.", "Payments are deducted automatically from your account each month.", "The system automatically saves your work every five minutes."],
    "bill":         ["He paid the electricity bill before the deadline.", "The restaurant bill came to eighty euros in total.", "She was shocked when she saw the phone bill this month."],
    "cabinet":      ["She kept her medicines in a locked cabinet.", "The cabinet decided to approve the new education policy.", "He built a wooden cabinet for the kitchen."],
    "cancer":       ["Early detection greatly increases the chances of surviving cancer.", "She raised money to support cancer research.", "He recovered from cancer after a long and difficult treatment."],
    "candidate":    ["All candidates must submit their application by Friday.", "She was the strongest candidate for the management position.", "The candidates debated live on television."],
    "carefully":    ["She read the contract carefully before signing it.", "He drove carefully on the icy road.", "Please listen carefully and follow the instructions."],
    "celebration":  ["The graduation celebration lasted all evening.", "They organized a small celebration for her promotion.", "New Year's is a time of celebration around the world."],
    "charity":      ["She donates a part of her salary to charity.", "The event raised thousands for a local children's charity.", "He volunteers at a charity that feeds homeless people."],
    "childhood":    ["She has wonderful memories of her childhood in the countryside.", "His difficult childhood made him stronger as an adult.", "Childhood friendships can last a lifetime."],
    "client":       ["She met with a new client to discuss the project.", "The lawyer kept his client's information strictly confidential.", "He always puts the needs of his clients first."],
    "committee":    ["She was elected to serve on the school committee.", "The committee meets once a month to review progress.", "The committee voted in favor of the new proposal."],
    "compete":      ["She trained hard to compete in the national championship.", "Small businesses often struggle to compete with large corporations.", "He competed against some of the best athletes in the world."],
    "conference":   ["She presented her research at an international conference.", "The annual conference brings together experts from many fields.", "He attended a conference on climate change in Geneva."],
    "confidence":   ["She spoke with great confidence during the presentation.", "Building confidence takes time and regular practice.", "His coach helped him regain his confidence after the defeat."],
    "confirm":      ["Please confirm your booking by replying to this email.", "She called to confirm the time of the appointment.", "Can you confirm that you received the documents?"],
    "consult":      ["He decided to consult a doctor about his back pain.", "She consulted her lawyer before signing the agreement.", "Always consult an expert before making a major financial decision."],
    "debt":         ["He worked hard to pay off his student debt.", "She managed to clear all her debts within two years.", "Getting into debt can cause long-term financial stress."],
    "deeply":       ["She was deeply moved by the kind words in the letter.", "He is deeply committed to protecting the environment.", "She felt deeply sorry for what had happened."],
    "eastern":      ["Eastern cultures often place great value on family and community.", "She traveled to several eastern European countries.", "The eastern part of the city has many historical buildings."],
    "elevator":     ["The elevator was out of order so they took the stairs.", "She pressed the button and waited for the elevator.", "He held the elevator door open for the woman with the pram."],
    "elsewhere":    ["If you can't find it here, try looking elsewhere.", "She decided to seek opportunities elsewhere after being passed over for promotion.", "He moved elsewhere to start a new chapter in his life."],
    "engineer":     ["She works as an engineer designing bridges.", "The engineer identified the fault in the machine.", "He studied hard to qualify as a civil engineer."],
    "enthusiasm":   ["She approached every task with great enthusiasm.", "His enthusiasm for the project inspired the rest of the team.", "The crowd cheered with enthusiasm as the team scored."],
    "essay":        ["She spent two days writing her history essay.", "The essay must be submitted before midnight on Friday.", "His essay was praised for its clear argument and strong evidence."],
    "establish":    ["She worked hard to establish herself in the industry.", "The organization was established over a hundred years ago.", "He established a strong relationship with his clients."],
    "excitement":   ["The excitement in the stadium grew as the final whistle approached.", "She could barely hide her excitement on the morning of the trip.", "There was a real sense of excitement about the new project."],
    "existing":     ["They decided to improve the existing system rather than replace it.", "The new law will affect all existing contracts.", "She built on the existing research to develop her own theory."],
    "expose":       ["The investigation exposed serious corruption in the company.", "She was exposed to different cultures while traveling.", "Don't expose your skin to the sun without sunscreen."],
    "fee":          ["There is a small fee for using the car park.", "The lawyer charged a reasonable fee for her services.", "Students in some countries pay no university tuition fees."],
    "friendship":   ["Their friendship grew stronger over many years.", "She values her friendship with him above almost everything.", "Good friendship is built on trust and mutual respect."],
    "gently":       ["She gently stroked the cat's fur.", "He gently reminded her that the deadline was approaching.", "The nurse gently explained the procedure to the patient."],
    "hell":         ["It was hell trying to find a taxi in the rain.", "She went through hell during the difficult months after the accident.", "He was determined not to give up — no matter what hell he faced."],
    "highway":      ["They drove along the highway for several hours.", "An accident on the highway caused a long traffic jam.", "The new highway reduced travel time between the two cities."],
    "historian":    ["The historian spent years researching medieval Europe.", "She is a respected historian who has written five books.", "The historian argued that the event changed the course of history."],
    "impressive":   ["Her performance in the final was truly impressive.", "The new office building is impressive both inside and out.", "He gave an impressive speech that everyone remembered."],
    "informal":     ["The meeting had a friendly and informal atmosphere.", "She used informal language in her text messages.", "The dinner was informal so there was no dress code."],
    "inspector":    ["The health inspector visited the restaurant to check standards.", "The inspector found several safety issues in the building.", "She was promoted to senior inspector after ten years on the force."],
    "judgment":     ["She showed good judgment in a very difficult situation.", "Try not to make quick judgments without knowing all the facts.", "His judgment was trusted by everyone on the team."],
    "latter":       ["She offered two options — she preferred the latter.", "Between study and work, the latter took up most of his time.", "The book is divided into two parts and the latter is more interesting."],
    "leader":       ["A good leader listens to everyone in the team.", "She became the leader of the project after impressing the managers.", "He is widely respected as a strong and fair leader."],
    "logical":      ["Her argument was clear, well-structured, and logical.", "The most logical solution is to address the root cause.", "He approached the problem in a calm and logical way."],
    "lonely":       ["She felt lonely during her first months in the new city.", "He reached out to a friend because he was feeling lonely.", "Moving abroad can be exciting but also lonely at times."],
    "mainly":       ["The film was mainly enjoyed by younger audiences.", "She works mainly from home during the week.", "The delay was mainly caused by bad weather."],
    "menu":         ["He studied the menu for several minutes before ordering.", "The restaurant added several new dishes to their menu.", "She asked the waiter for a menu as soon as she sat down."],
    "merely":       ["She was merely trying to help — she meant no harm.", "The comment was merely a suggestion, not a criticism.", "He is not merely a colleague — he is also a close friend."],
    "mine":         ["That seat is mine — I left my jacket on it.", "She said the idea was originally mine.", "The workers spent long hours down in the mine."],
    "moreover":     ["The hotel was clean and comfortable; moreover, the staff were very helpful.", "She is talented; moreover, she works incredibly hard.", "The price is reasonable; moreover, delivery is free."],
    "net":          ["She earns a good net salary after tax.", "He caught three fish in the net.", "The company's net profit increased by fifteen percent this year."],
    "novel":        ["She stayed up all night to finish reading the novel.", "He wrote his first novel while working as a teacher.", "The novel explores themes of love, loss, and identity."],
    "obtain":       ["She worked hard to obtain the qualifications she needed.", "You must obtain permission before using the photos.", "He finally obtained his driving license after three attempts."],
    "ought":        ["You ought to apologize for what you said.", "She ought to see a doctor if the pain continues.", "He ought to have called before arriving unannounced."],
    "owe":          ["She owes him a sincere apology.", "He owes the bank a large amount of money.", "I owe you one — thanks for covering for me today."],
    "panic":        ["Don't panic — everything is under control.", "She panicked when she couldn't find her passport.", "There was widespread panic when the alarm went off."],
    "participate":  ["She encouraged all students to participate in the discussion.", "Everyone is welcome to participate in the community event.", "He participated in a charity run and raised two hundred euros."],
    "patience":     ["Patience is one of the most important qualities a teacher can have.", "She showed great patience while waiting for the results.", "Learning a language requires time, effort, and patience."],
    "pattern":      ["She noticed a clear pattern in the data.", "The fabric had a beautiful floral pattern.", "His behavior follows a familiar pattern whenever he is stressed."],
    "physically":   ["She felt physically exhausted after the long hike.", "The job is physically demanding and requires a lot of stamina.", "He was both mentally and physically drained by the end of the day."],
    "poem":         ["She wrote a poem for her mother's birthday.", "He read a beautiful poem at the wedding ceremony.", "The poem was short but full of powerful emotion."],
    "poet":         ["She became a celebrated poet in her thirties.", "The poet used vivid imagery to describe nature.", "He is considered one of the greatest poets of the twentieth century."],
    "poetry":       ["She discovered a love for poetry in high school.", "His poetry is known for its honesty and deep emotion.", "Poetry allows people to express feelings that are hard to put into words."],
    "pollution":    ["Air pollution in the city has reached dangerous levels.", "The factory was fined for causing water pollution in the river.", "Reducing pollution is one of the biggest challenges of our time."],
    "possibility":  ["There is a real possibility that the event will be cancelled.", "She considered every possibility before making her decision.", "He was excited by the possibility of moving to a new country."],
    "previously":   ["She had previously worked at a hospital before joining the clinic.", "He had previously failed the exam twice before passing.", "The building was previously used as a school."],
    "professor":    ["The professor delivered a fascinating lecture on ancient Rome.", "She asked her professor for advice on her research topic.", "He became a professor after twenty years of research in his field."],
    "refrigerator": ["She kept the leftovers in the refrigerator for the next day.", "The refrigerator stopped working and all the food went bad.", "He opened the refrigerator looking for something to eat."],
    "region":       ["The northern region of the country is known for its forests.", "She works for an organization that supports rural regions.", "Tourism in the region has increased significantly in recent years."],
    "remarkable":   ["She made a remarkable recovery after her operation.", "It is remarkable how much he has improved in just six months.", "The view from the top of the mountain was truly remarkable."],
    "remind":       ["Can you remind me to call him tomorrow morning?", "The smell of fresh bread reminded her of her childhood.", "He set an alarm to remind himself of the appointment."],
    "reputation":   ["She has built a strong reputation as a reliable professional.", "The restaurant's reputation for quality food brought in many customers.", "One mistake can seriously damage a company's reputation."],
    "resist":       ["She tried hard to resist eating the last slice of cake.", "He could not resist helping when he saw someone in trouble.", "It was impossible to resist the smell of freshly baked cookies."],
    "response":     ["She got a positive response to her job application.", "His response to the crisis was calm and effective.", "The charity received an overwhelming response to its fundraising campaign."],
    "retain":       ["She used flashcards to help retain new vocabulary.", "The company worked hard to retain its best employees.", "It can be difficult to retain information when you are tired."],
    "reveal":       ["The documentary revealed shocking facts about the food industry.", "She finally revealed where she had hidden the present.", "The investigation revealed that the data had been falsified."],
    "roughly":      ["It takes roughly thirty minutes to get there by bus.", "The project will cost roughly five thousand euros.", "She arrived at roughly the same time every morning."],
    "salary":       ["He negotiated a higher salary before accepting the job offer.", "Her salary increased after her annual performance review.", "A competitive salary is one of the most important factors when choosing a job."],
    "sample":       ["She gave customers a free sample of the new product.", "The doctor took a blood sample for testing.", "He asked for a sample before placing a large order."],
    "scheme":       ["The government launched a scheme to help first-time buyers.", "She came up with a clever scheme to reduce waste at work.", "He joined a savings scheme to help build an emergency fund."],
    "script":       ["She spent weeks writing the script for the film.", "He memorized his lines from the script the night before.", "The script was rewritten several times before filming began."],
    "solution":     ["She found an elegant solution to the technical problem.", "There is no simple solution to the issue of climate change.", "The team brainstormed solutions together for over an hour."],
    "southern":     ["The southern part of the country has a warmer climate.", "She grew up in a small town in the southern region.", "Southern cuisine is known for its rich flavors and bold spices."],
    "suck":         ["It really sucks when your plans fall apart at the last minute.", "The old vacuum cleaner didn't suck up the dust properly.", "He admitted that losing the match sucked but said he would train harder."],
    "tale":         ["She read her children a bedtime tale every night.", "The old sailor told a fascinating tale of adventure at sea.", "It is a tale of love, loss, and finding hope again."],
    "temporary":    ["She took a temporary job while looking for something permanent.", "The road is closed temporarily while repairs are being made.", "He found a temporary place to stay while his flat was being renovated."],
    "tight":        ["She was on a tight budget this month.", "The lid was too tight and she couldn't open the jar.", "They had a tight deadline and worked through the weekend."],
    "tourist":      ["The city attracts millions of tourists every year.", "She joined a guided tour for tourists visiting the old town.", "He was surprised by how crowded the tourist sites were in summer."],
    "tradition":    ["It is a tradition in her family to have a big meal together on Sundays.", "He respects local traditions when traveling to new places.", "The tradition of giving gifts at Christmas is celebrated worldwide."],
    "trainer":      ["Her personal trainer helped her prepare for the marathon.", "The trainer gave the team feedback after each session.", "He became a fitness trainer after years of working in sport."],
    "twice":        ["She has visited Japan twice and hopes to go again.", "He knocked on the door twice but got no answer.", "The doctor told her to take the tablet twice a day."],
    "unfortunately": ["Unfortunately, the event was cancelled due to bad weather.", "She worked hard, but unfortunately did not get the promotion.", "Unfortunately, we don't have any tables available tonight."],
    "union":        ["The workers formed a union to fight for better conditions.", "She joined the student union in her first year of university.", "The union negotiated a pay rise for all its members."],
    "upper":        ["The upper floors of the building have the best views.", "She grew up in an upper-middle-class family.", "He placed the box on the upper shelf."],
    "vegetable":    ["She adds a variety of vegetables to every meal.", "Eating vegetables every day is essential for good health.", "He grew his own vegetables in the garden."],
    "vehicle":      ["The vehicle broke down on the side of the motorway.", "Only authorised vehicles are allowed to park in this area.", "She learned to drive a variety of vehicles during her training."],
    "west":         ["The sun sets in the west every evening.", "She moved to the west of the country for a fresh start.", "He drove west along the coast, enjoying the ocean views."],
    "winner":       ["She was announced as the winner of the competition.", "The winner received a trophy and a cash prize.", "Everyone was surprised by the winner — nobody had expected it."],

    # ── B2 ────────────────────────────────────────────────────────────────────
    "advanced":     ["She enrolled in an advanced English course to improve her fluency.", "The technology is too advanced for many consumers to understand.", "He received advanced training before being assigned the role."],
    "agency":       ["She contacted a recruitment agency to find a new job.", "The advertising agency created a highly successful campaign.", "He worked for a government agency dealing with environmental issues."],
    "alternative":  ["She looked for an alternative when the first plan failed.", "Using public transport is a good alternative to driving.", "He offered two alternatives and let her choose."],
    "analysis":     ["The analysis showed that sales had dropped by ten percent.", "She carried out a detailed analysis of the survey results.", "A careful analysis of the data revealed some surprising patterns."],
    "anxiety":      ["She experiences anxiety before public speaking.", "Regular exercise can help reduce feelings of anxiety.", "His anxiety grew as the exam date got closer."],
    "association":  ["She joined a professional association for teachers.", "There is a strong association between smoking and lung disease.", "The association holds an annual conference for its members."],
    "atmosphere":   ["The restaurant had a warm and welcoming atmosphere.", "Scientists are studying changes in the Earth's atmosphere.", "The atmosphere in the room changed when he walked in."],
    "combination":  ["The combination of hard work and talent led to her success.", "The dish had an unusual but delicious combination of flavors.", "A combination of factors caused the project to fail."],
    "commercial":   ["The commercial break lasted longer than the programme itself.", "The area has been developed for commercial use.", "She left her art career to pursue commercial photography."],
    "communicate":  ["It is important to communicate clearly in any relationship.", "She communicated her concerns to the manager directly.", "He finds it difficult to communicate his feelings."],
    "concept":      ["The concept of the project was brilliant but hard to execute.", "She struggled to grasp the concept at first but eventually understood.", "He explained the concept clearly with a simple diagram."],
    "confusion":    ["There was some confusion about the meeting time and location.", "The new policy caused confusion among employees.", "She apologized for any confusion her message may have caused."],
    "cultural":     ["Studying abroad gave her valuable cultural experiences.", "Cultural differences can sometimes lead to misunderstandings.", "He has a deep appreciation for cultural diversity."],
    "designer":     ["She hired a designer to redesign the company logo.", "He is a well-known fashion designer based in Milan.", "The interior designer transformed the small flat into a beautiful space."],
    "director":     ["The director called for another take of the key scene.", "She was promoted to director of marketing after five years.", "The director's vision was clear from the very first meeting."],
    "disaster":     ["The flood was the worst natural disaster in decades.", "The product launch turned into a complete disaster.", "She helped coordinate relief efforts after the disaster."],
    "discipline":   ["Success in sport requires incredible discipline and dedication.", "The teacher maintained discipline in the classroom calmly.", "She set herself strict rules to develop better self-discipline."],
    "dramatic":     ["The team made a dramatic comeback in the final minutes.", "There has been a dramatic increase in online shopping.", "He delivered a dramatic speech that left the audience speechless."],
    "economics":    ["She studied economics at university before going into finance.", "Understanding basic economics can help you manage your money better.", "The economics of running a small business can be very challenging."],
    "effectively":  ["She communicated her ideas effectively to the whole team.", "The medicine treated the infection quickly and effectively.", "He managed the situation effectively despite the pressure."],
    "emphasis":     ["The teacher placed great emphasis on reading and writing.", "The company's emphasis on quality has helped build a loyal customer base.", "She spoke with emphasis to make sure the key point was understood."],
    "emphasize":    ["He emphasized the importance of staying hydrated during exercise.", "She emphasized that the deadline could not be extended.", "The report emphasizes the need for urgent action on climate change."],
    "employer":     ["Her employer was very understanding about her family situation.", "A good employer values the wellbeing of their staff.", "He was impressed by the employer's commitment to work-life balance."],
    "engineering":  ["She chose engineering because she loves solving real-world problems.", "Civil engineering projects like bridges and roads shape our cities.", "He received a scholarship to study engineering abroad."],
    "entertainment": ["The festival offered a full day of entertainment for all ages.", "Streaming services have changed the entertainment industry.", "She works in entertainment as a producer for a TV company."],
    "essentially":  ["The two proposals are essentially the same with minor differences.", "He essentially ran the department on his own for six months.", "The argument is essentially about who is responsible."],
    "estate":       ["She inherited a large estate in the countryside.", "The real estate market in the city is very competitive.", "He sold his estate to fund his retirement."],
    "estimate":     ["The builder gave us an estimate for the cost of repairs.", "She estimated that the project would take around three months.", "His estimate turned out to be very close to the actual figure."],
    "examination":  ["She studied hard in preparation for her final examination.", "The doctor carried out a full physical examination.", "He passed all three examinations on his first attempt."],
    "extreme":      ["She went to extreme lengths to ensure everything was perfect.", "The athletes competed in extreme conditions with freezing temperatures.", "He expressed his opinion in extreme terms, which upset some people."],
    "federal":      ["The federal government announced a new housing policy.", "She works for a federal agency that regulates food safety.", "Federal law applies to all citizens regardless of which state they live in."],
    "global":       ["Climate change is one of the most pressing global challenges.", "The company expanded its operations to reach a global audience.", "She is passionate about finding global solutions to local problems."],
    "guidance":     ["She provided clear guidance to the new members of the team.", "He sought guidance from a career counselor before making his decision.", "The report offers practical guidance for businesses looking to reduce emissions."],
    "importance":   ["She stressed the importance of communication in any relationship.", "Understanding the importance of sleep can improve your overall health.", "The importance of the discovery was recognized worldwide."],
    "independence": ["She valued her independence and preferred to live alone.", "The country celebrated fifty years of independence.", "He encouraged his children to develop independence from an early age."],
    "management":   ["She completed a course in project management.", "Good time management is one of the most useful skills you can develop.", "The management team met every Monday morning to review progress."],
    "occasionally": ["She occasionally works late when there is a tight deadline.", "He occasionally visits his hometown to see old friends.", "Occasionally, the system crashes but it usually fixes itself quickly."],
    "pace":         ["She walked at a brisk pace to get there on time.", "He set the pace during the first half of the race.", "Learning at your own pace makes the process much more enjoyable."],
    "perspective":  ["Traveling gives you a fresh perspective on your own culture.", "She tried to see the situation from his perspective.", "It is important to consider different perspectives before making a decision."],
    "preparation":  ["Good preparation is the key to a successful presentation.", "She began her preparation for the exam two months in advance.", "The team spent weeks in preparation for the big launch."],
    "presentation": ["She gave a confident and well-structured presentation.", "He was nervous before the presentation but did brilliantly.", "The presentation was supported by clear slides and real data."],
    "regularly":    ["She exercises regularly to maintain her fitness.", "He checks his emails regularly throughout the working day.", "It is important to visit your dentist regularly."],
    "significantly": ["The new system significantly reduced the time needed for each task.", "Her grades improved significantly after she changed her study approach.", "Air quality has improved significantly since the new regulations were introduced."],
    "strategy":     ["The company developed a clear strategy for entering new markets.", "She explained her strategy for passing the exam in six weeks.", "A good strategy is essential for long-term success in business."],
    "suitable":     ["This film is not suitable for young children.", "She chose a suitable moment to raise the issue.", "He wore a suit that was suitable for the formal occasion."],
    "visual":       ["The presentation used strong visual elements to support the data.", "She has a great visual sense and always designs beautiful layouts.", "Visual learning works well for people who think in pictures."],

    # ── C1 ────────────────────────────────────────────────────────────────────
    "administrative": ["She handles all administrative tasks for the department.", "The administrative process for applying can take several weeks.", "He was promoted to an administrative role after years in the field."],
    "comprehensive":  ["The report provided a comprehensive overview of the situation.", "She underwent a comprehensive medical check-up.", "The course offers a comprehensive introduction to the subject."],
    "contribution":   ["Her contribution to the project was invaluable.", "He made a generous financial contribution to the charity.", "Everyone's contribution, no matter how small, makes a difference."],
    "educational":    ["The documentary was both entertaining and educational.", "She volunteered at an educational program for underprivileged children.", "The museum provides educational resources for school visits."],
    "environmental":  ["The company adopted new environmental policies to reduce waste.", "She studies environmental science to understand climate change.", "Environmental protection is a responsibility we all share."],
    "indication":     ["Rising temperatures are a clear indication of climate change.", "There was no indication that anything had gone wrong.", "His reluctance to answer was a strong indication that he was hiding something."],
    "initiative":     ["She took the initiative and organized the team before anyone asked.", "The government launched a new initiative to support small businesses.", "He was praised for his initiative in solving the problem independently."],
    "leadership":     ["Strong leadership is essential during times of crisis.", "She demonstrated excellent leadership skills throughout the project.", "The course includes a module on leadership and team management."],
    "literature":     ["She developed a deep love for literature at an early age.", "The course covers both classic and contemporary literature.", "His contribution to English literature has been widely recognized."],
    "maintenance":    ["Regular maintenance can extend the lifespan of any machine.", "The building is closed for maintenance this weekend.", "She is responsible for the maintenance of the company's IT systems."],
    "manufacturer":   ["The manufacturer recalled the product due to a safety issue.", "She works in quality control for a car manufacturer.", "The manufacturer offers a two-year warranty on all its products."],
    "measurement":    ["Accurate measurement is critical in scientific research.", "She took careful measurements before cutting the fabric.", "The measurement of progress in education is a complex challenge."],
    "negotiation":    ["The negotiation between the two companies lasted several days.", "She has excellent negotiation skills and always reaches a fair deal.", "Successful negotiation requires listening as well as talking."],
    "objective":      ["Her main objective was to finish the project on time.", "Try to stay objective when evaluating your own work.", "The team set clear objectives at the start of the quarter."],
    "perception":     ["His perception of the situation was very different from hers.", "Media coverage can shape public perception of an issue.", "She challenged the perception that success only comes from hard work."],
    "proposal":       ["He submitted a detailed proposal for the new project.", "She accepted his marriage proposal with tears of joy.", "The committee reviewed the proposal and asked for further details."],
    "psychology":     ["She studied psychology to better understand human behavior.", "He applied principles of psychology to improve his coaching style.", "The psychology behind consumer choices is a fascinating area of research."],
    "revenue":        ["The company's revenue grew by twenty percent last year.", "Advertising is a major source of revenue for social media platforms.", "She analyzed the revenue streams to identify where growth was possible."],
    "revolution":     ["The industrial revolution transformed the way people lived and worked.", "Social media has caused a revolution in how we communicate.", "The revolution led to a complete change in the country's political system."],
    "specify":        ["Please specify your preferred delivery date when ordering.", "The contract does not specify who is responsible for repairs.", "She asked him to specify exactly what he needed from the report."],
}


def main():
    print(f"Loading vocabulary from:\n  {VOCAB_JSON_PATH}\n")
    with open(VOCAB_JSON_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)

    updated = 0
    not_found = []

    for level in data["levels"]:
        for word_entry in level["words"]:
            word = word_entry["word"]
            if word in SENTENCES:
                word_entry["sentences"] = SENTENCES[word]
                updated += 1

    # Check which flagged words are NOT in our dictionary
    flagged_path = Path(__file__).parent / "flagged_words.json"
    if flagged_path.exists():
        with open(flagged_path) as f:
            flagged = json.load(f)
        for fw in flagged:
            if fw["word"] not in SENTENCES:
                not_found.append(fw["word"])

    print(f"Saving updated vocabulary.json...")
    with open(VOCAB_JSON_PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"Done! Updated {updated} words with hand-crafted sentences.")
    if not_found:
        print(f"\nMissed {len(not_found)} flagged words (no sentences written for them):")
        for w in not_found:
            print(f"  - {w}")


if __name__ == "__main__":
    main()
